### ISSUE TITLE
alarm on mac

### ISSUE THREAD

**Issue by Jwink3101** [rukshn/pomodoro#4]
If you wanted to alarm on mac, you can do something like

```
say -v bells "beep"
```

which works fine.

**Comment by seagoj** [comment]
I don't have a Mac to test my changes with, but I have a potential fix if you want it.

It's not the cleanest thing in the world because the frequency and duration of the  Linux alarm are passed (I think rightly so for ease of configuration) into the _alarm function, but are not used at all for the mac side. I'd be happy to rework it if someone has a suggestion.
